### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by SimonBiggs** [rickardcronholm/gammaValidation#1]
Heya Rickard,

Would you be able to provide a license file with this gamma validation code? I was hoping to be able to include it within http://pymedphys.com as a way to independently calculate gamma next to the other gamma methods I have provided there.

Cheers,
Simon

**Comment by rickardcronholm** [comment]
Sure, what license do you recommend?

Btw, I saw npgamma mentioned in a scikit machine learning presentation
rwcently. Pretty cool

Den lör 24 nov. 2018 08:38 skrev Simon Biggs <notifications@github.com>:

**Comment by SimonBiggs** [comment]
Oh wow really? That is interesting. What was the context of the scikit
presentation? Is it available on YouTube by any chance?

The following is a great resource to pick a license
https://choosealicense.com.

It's less complicated on my end if you pick the same license as I have
decided to stick with. Which is the same as the license that EGSnrc uses,
the AGPLv3+ license. I chose it because I wanted derivatives to stay open
source.

If you don't mind whether or not derivatives also share their source code
under the same license then the Apache license is a good one.

Hope you're doing well :),
Cheers,
Simon

**Comment by rickardcronholm** [comment]
I'll fix the license on Monday.

It is on Youtube
https://www.google.se/url?sa=t&source=web&rct=j&url=https://m.youtube.com/watch%3Fv%3DBjF3Z2gJQbY&ved=2ahUKEwi1k8_y1tDeAhUilosKHYuDBpEQjjgwAHoECAkQAQ&usg=AOvVaw07o0guFa-G1CMrcn34BHKp

The context was machine learning as dose calculation (or rather dose
prediction). Really cool idea. Npgamma was used to evaluate against the
reference dose.

Whats going on with conehead? Is it actively developed? It has tremendous
potential. Eapecially if it can utilize gpu acceleration.

Den lör 24 nov. 2018 13:16 skrev Simon Biggs <notifications@github.com>:

**Comment by SimonBiggs** [comment]
Ah yes. Definitely very cool. I had actually seen that. Roy was chatting
with me leading up to the talk.

I agree that conehead has massive potential. I'm not sure if he is going
down the GPU path, but if it was programmed using numba instead of cython
you would get CUDA for free...

I was experimenting a little with a collapsed code algorithm:
https://gitlab.com/pymedphys/pymedphys/tree/master/experimentation/collapsedcone

I'm not sure if Samuel Peet is ready for others to work on conehead with
him. Maybe it would be worthwhile doing some work in parallel? What do you
think? Would you be willing to dive a bit into working on a collapsed cone
algorithm with me? With the aim to run on numba --> GPU?

**Comment by rickardcronholm** [comment]
I would certainly be interested. Not sure how much time I could devote.
Depends on wether I can convince my employer that it is a tool we can use.
It could serve a purpose in our perfermance testing so there are legit
argument.

There could also be a few killer application based on it in the field of
adaptive rt. Especially if it gets fast enough. Im sure you could think of
a few application as well. Come to think of it, maybe it could be useful to
have a brainstorming session with you if you are interested. My company are
largely focused on AI in imaging and radiotherapy.

Den lör 24 nov. 2018 13:34 skrev Simon Biggs <notifications@github.com>:

**Comment by SimonBiggs** [comment]
Ahh neat. Have you moved where you work? I had also thought that AI could
be used to train the residual distance/dose between a GPU based collapsed
cone and Monte Carlo. It would mean it wouldn't need to make widely huge
predictions just small improvement tweaks. Could be quite fast, and
potentially as accurate as a many histories Monte Carlo.

It wouldn't have the same black boxiness as a standard AI based dose calc
as, you could have a way to display the underlying collapsed cone, and then
the residual shifts the AI applied, as well as have it flag if it shifted
anything beyond a certain threshold.

So, having a GPU collapsed cone algorithm could align with your companies
desires.

Let me know your thoughts,
Cheers,
Simon
